### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by gabrielfreire** [bjornna/simple-example-dotnet-cli#1]
Hi @bjornna , nice example. 

I am a .NET developer learning about OpenEHR and just found your CLI example, I cloned it to try myself but   the **DIPS.OpenEhr** package doesn't seem to exist anymore, is there any other package available or setup required ?

**Comment by bjornna** [comment]
I am sorry. The **DIPS.OpenEhr** package is an internal package which is not available currently. Sorry for not making this clearer for you and other interested people.

**Comment by gabrielfreire** [comment]
Thanks for your reply @bjornna, could you send me the JSON output of your loadWeights method so I can get an idea of what is going on ? 

It would be very helpful as well if I could have a look at the CompositionBuilder and Json Serializer source-code if that's ok, thank you.
